# Generated by Django 4.1.5 on 2023-01-10 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='company_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('body', models.TextField()),
                ('agent', models.CharField(max_length=255)),
                ('data_added', models.DateTimeField(auto_now_add=True)),
                ('create_user_company', models.CharField(max_length=255)),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
