# Generated by Django 4.1.5 on 2023-01-10 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camos_app', '0002_alter_users_company_name_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('experience', models.BooleanField(default=False)),
                ('construction1', models.CharField(max_length=255)),
                ('construction2', models.CharField(max_length=255)),
                ('construction3', models.CharField(max_length=255)),
                ('create_user', models.CharField(max_length=255)),
                ('create_user_company', models.CharField(max_length=255)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camos_app.post')),
            ],
        ),
    ]
